SELECT *FROM ORDERS
SELECT *FROM WEB_EVENTS
SELECT *FROM ACCOUNTS
SELECT *FROM REGION
SELECT *FROM SALES_REPS;

SELECT O.* , E.CHANNEL
FROM ORDERS O
JOIN WEB_EVENTS E
ON O.account_id = E.account_id;


SELECT *
FROM ACCOUNTS A
JOIN WEB_EVENTS E
ON A.id = E.account_id;