
CREATE DATABASE COMMAND 

CREATE TABLE STUDENTS (
ID INT PRIMARY KEY,
NAME VARCHAR(20),
GEDER CHAR(1),
AGE INT
)
SELECT*FROM STUDENTS;

INSERT INTO STUDENTS(ID,NAME,GEDER,AGE)
VALUES
(1,'AYO', 'M', 14)